<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>


	<ItemGroup>
		<PackageReference Include="CryptoPrice" Version="0.0.3" />
		<PackageReference Include="Nethereum.JsonRpc.WebSocketClient" Version="5.0.0" />
		<PackageReference Include="Nethereum.RPC.Reactive" Version="5.0.0" />
		<PackageReference Include="Nethereum.Accounts" Version="5.0.0" />
		<PackageReference Include="Nethereum.Web3" Version="5.0.0" />
		<PackageReference Include="Nethereum.Signer" Version="5.0.0" />
		<PackageReference Include="Nethereum.Contracts" Version="5.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
		<PackageReference Include="System.Net.WebSockets" Version="4.3.0" />
		<PackageReference Include="System.Reactive" Version="6.0.1" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	</ItemGroup>


	<ItemGroup>
    <ProjectReference Include="..\CoinBank.Domain\CoinBank.Domain.csproj" />
  </ItemGroup>


	<ItemGroup>
	  <Folder Include="_Common\Services\" />
	  <Folder Include="_PreSaleRelease\DTOs\Updates\" />
	  <Folder Include="_Price\DTOs\Updates\" />
	</ItemGroup>

</Project>
