<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>


	<ItemGroup>
		<PackageReference Include="CryptoPrice" />
		<PackageReference Include="Nethereum.JsonRpc.WebSocketClient" />
		<PackageReference Include="Nethereum.RPC.Reactive" />
		<PackageReference Include="Nethereum.Accounts" />
		<PackageReference Include="Nethereum.Web3" />
		<PackageReference Include="Nethereum.Signer" />
		<PackageReference Include="Nethereum.Contracts" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" />
		<PackageReference Include="System.Net.WebSockets" />
		<PackageReference Include="System.Reactive" />
		<PackageReference Include="SixLabors.ImageSharp" />
	</ItemGroup>


	<ItemGroup>
    <ProjectReference Include="..\CoinBank.Domain\CoinBank.Domain.csproj" />
  </ItemGroup>


	<ItemGroup>
	  <Folder Include="_Price\DTOs\Updates\" />
	</ItemGroup>

</Project>
